// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFj7mXVUrPbvAPziZYt659r0Q3v4nooUU',
    appId: '1:894102880238:android:0b2f0908c40d35fedb58ff',
    messagingSenderId: '894102880238',
    projectId: 'todouser-e3b8f',
    storageBucket: 'todouser-e3b8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0topH6RnIfGRI-d7jVnGxhmCcCY2ysfk',
    appId: '1:894102880238:ios:e3c4c9ded2134bcadb58ff',
    messagingSenderId: '894102880238',
    projectId: 'todouser-e3b8f',
    storageBucket: 'todouser-e3b8f.firebasestorage.app',
    iosBundleId: 'com.example.firebase007',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmt5GkNmD3YqPmIKr-htvr-RwE2CPO164',
    appId: '1:894102880238:web:391a027c43eff534db58ff',
    messagingSenderId: '894102880238',
    projectId: 'todouser-e3b8f',
    authDomain: 'todouser-e3b8f.firebaseapp.com',
    storageBucket: 'todouser-e3b8f.firebasestorage.app',
    measurementId: 'G-CJC87S36ML',
  );
}
